version: "3"

services:
  matomo_db:
    container_name: matomo_db
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD_PLACEHOLDER
    env_file:
      - ./db.env

  matomo_app:
    container_name: matomo_app
    image: matomo:fpm-alpine
    restart: always
    volumes:
      - ./config:/var/www/html/config:z
      - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    depends_on:
      - matomo_db

  matomo_cron:
    container_name: matomo_cron
    image: matomo:fpm
    depends_on:
      - matomo_app
    volumes:
      - matomo:/var/www/html:rw
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'

  matomo_web:
    container_name: matomo_web
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:z,ro
      - ./ssl-certs/:/etc/netgamers.it/
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - A_VALID_PORT:443
    depends_on:
      - matomo_app

volumes:
  db:
  matomo:
